### ISSUE TITLE
Problem: I don't have a writing utensil

### ISSUE THREAD

**Issue by AdrianusCornet** [Codaisseur/fullstack-labs#8]
Summary:
My pencil does not work and I don't have a backup pencil.

Steps to reproduce:
1. Get my pencil out of the red trash can in the classroom.
1. Try to write with it.

Expected result:
A line appears on paper.

Actual result:
Nothing appears on paper.

**Comment by jelle89** [comment]
Have you tried licking the paper? I have heard that it can resolve the issue. It was either licking the paper, or licking the pen. I can't remember

**Comment by AdrianusCornet** [comment]
I got a blue pen, it should work temporarily.
